## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
b = np.array([67,89,34,23,12])

print(b)

[67 89 34 23 12]


In [28]:
print(a.shape)

(10,)


In [29]:
print(b.shape)

(5,)


In [22]:
print(a.dtype)

int64


In [23]:
print(type(a))

<class 'numpy.ndarray'>


In [27]:
print(a.min())

1


In [26]:
print(a.max())

10


In [31]:
# 2-D array 
a = np.array([[1,2,3,4],[5,6,7,8]]) # four columns and two rows
print(a)
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
print(a.ndim)

2


In [35]:
a = np.array([[1,2],[5,6],[7,8]]) # 2d array two columns and three rows 
print(a)
print(a.ndim)

[[1 2]
 [5 6]
 [7 8]]
2


In [37]:
print(a.size)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)
print(a.data)
print(type(a))
print(a)

6
2
(3, 2)
int64
8
<class 'numpy.ndarray'>
[[1 2]
 [5 6]
 [7 8]]


In [40]:
a.ravel() # convert the 2D- array into 

array([1, 2, 5, 6, 7, 8])

In [42]:
a = np.arange(5) # arrange function sequentially of integer 
print(a)

[0 1 2 3 4]


In [43]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
# Reshape function reshaping the array into rows and columns
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
# np.arange(start, end, skip/ jump)
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


In [49]:
b = np.arange(5,50,5)
print(b)

[ 5 10 15 20 25 30 35 40 45]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print(type(arr))
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
(12,)


In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1.reshape(1,5) # One row and five columns

array([[1, 2, 3, 4, 5]])

In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [8]:
np.arange(0, 10, 1).reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Numpy Vectories Opration
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

## Element addition 

print(arr1 + arr2)

[ 7  9 11 13 15]


In [16]:
# Element wise subtraction 
print(arr1 - arr2)

[-5 -5 -5 -5 -5]


In [50]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [51]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [52]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [53]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:

print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [55]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [56]:

arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [57]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [58]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [59]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [60]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [61]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [62]:
np.random.rand(3,3)

array([[0.96706259, 0.19055119, 0.23355223],
       [0.43955233, 0.51241526, 0.82926245],
       [0.02034164, 0.69012607, 0.24491943]])

In [66]:
np.random.randint(1, 10, size=(3, 3))

array([[6, 7, 1],
       [7, 4, 2],
       [3, 7, 5]], dtype=int32)

In [67]:
np.random.randn(3, 3)

array([[ 1.1417946 ,  0.10208393, -0.02566986],
       [-0.70092438, -0.10258875,  0.60729664],
       [ 0.27026524, -0.23665931, -0.9382686 ]])