In [1]:
# 1 Write a Program that converts Celsius to Fahrenheit temp 

def Cel_to_Fahrenheit(celsius):
    return (celsius * 9/5) + 32 
    
print(Cel_to_Fahrenheit(25))

77.0


In [10]:
# 2 Write a program that swaps two variables without using temp variable.

def swap_without_temp(a, b):
    return b, a

result = swap_without_temp(5, 10)

print(f"Before swapping : a = {result[0]}, b = {result[1]}")
print(f"After swapping  : a = {result[1]}, b = {result[0]}")

Before swapping : a = 10, b = 5
After swapping  : a = 5, b = 10


In [20]:
# 3 Write a program that converts RGB to HEX 

def rgb_to_hex(r, b, g):
    return f"{((r<<16) + (g<<8) + b):06X}"
    
print(rgb_to_hex(0, 50, 255))


00FF32


In [23]:
# 4 Write a program that transpose of a Matrix

def transpose_matrix(matrix):
    return [list(row) for row in zip(*matrix)]

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("\n".join(",".join(map(str, row)) for row in transpose_matrix(matrix)))

1,4,7
2,5,8
3,6,9


In [27]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transposed_matrix = matrix.T
print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
# 5 Write a program that checks if the date is valid 

from datetime import datetime

def is_date_valid(val):
    return datetime.strptime(val, "%B %d, %Y %H:%M:%S") 

print(is_date_valid("December 17, 1995 03:24:00"))

1995-12-17 03:24:00


In [35]:
# 6 Write a program that FIND THE DAY OF YEAR 
from datetime import datetime
def day_of_year(date):
    return date.timetuple().tm_yday

print(day_of_year(datetime(2040,10,1)))

275


In [36]:
# 7 Write a program that CAPITALIZE A STRING FRIST CHARACTER 

def cap_first(S):
    return S[0].upper() + S[1:] if S else ""

print(cap_first("follow for more"))

Follow for more


In [37]:
# 8 Write a Python Program that FIND THE NUMBER OF DAYS BETWEEN TWO DAYS 

from datetime import datetime
def day_diff(date1, date2):
    return abs((date2 - date1).days) + 1

date1 = datetime(2020,10,21)
date2 = datetime(2021,10,22)

print(day_diff(date1, date2))


367


In [39]:
# 9 Write a Python program that FINDS THE FREQUENCY OF CHARACTER IN A STRING 
def freq(String):
    return{char:String.count(char) for char in set(String)}

print(",".join([f"{k}={v}" for k, v in freq("hello").items()]))

l=2,e=1,h=1,o=1


In [42]:
# 10 Write a Python program that  GENERATE RANDOM HEX 
import random
def random_hex():
    return f"{random.randint(0,0xFFFFFF):06X}"

print(random_hex())

9ADF0A
