# 1 Write a Python program to generate a Star triangle 

In [6]:
def triangle(rows):
    # Loop through each row
    for i in range(1, rows + 1):
        # Print i stars for the current row
        print('*' * i)

# Example usage:
num_rows = int(input("n:" ))
triangle(num_rows)

n: 7


*
**
***
****
*****
******
*******


# 2 Write a program to produce the Fibonacci series in Python.

In [7]:
def fibs(n):
    fib_sequence = []
    a, b = 0, 1
    for _ in range(n):
        
        fib_sequence.append(a)
        
        a, b = b, a + b
        
    return fib_sequence

# Example usage:
num_terms = int(input())
print(fibs(num_terms))

 12


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


# 3 Make a Python program that checks if a sequence is a Palindrome.

In [10]:
a=input("enter sequence")
b=a[::-1]
if a==b:
  print("palindrome")
else:
  print("Not a Palindrome")

enter sequence 323


palindrome


# 4 Can you write a sorting algorithm with a numerical dataset?

In [17]:
list = ["1", "4", "0", "6", "9"]

list = [int(i) for i in list]

list.sort()

print (list)

[0, 1, 4, 6, 9]


# 5  Can you write a sorting algorithm with a numerical dataset? but without using inbuild methods like sort 

In [18]:
def bubble_sort(nums):
    n = len(nums)
    # Traverse through all elements in the list
    for i in range(n):
        # Last i elements are already sorted, so we don't need to check them
        for j in range(0, n - i - 1):
            # Swap if the element found is greater than the next element
            if nums[j] > nums[j + 1]:
                nums[j], nums[j + 1] = nums[j + 1], nums[j]

# Example usage:
data = [64, 34, 25, 12, 22, 11, 90]
bubble_sort(data)
print("Sorted array is:", data)

Sorted array is: [11, 12, 22, 25, 34, 64, 90]


# 6 Write a program that checks if all of the numbers in a sequence are unique.

In [19]:
def are_all_unique(sequence):
    seen = set()  # Set to store encountered numbers
    for num in sequence:
        if num in seen:
            return False  # If the number is already in the set, it's not unique
        seen.add(num)  # Add the number to the set
    return True  # If all numbers are unique, return True


# Example usage:
sequence1 = [1, 2, 3, 4, 5]
sequence2 = [1, 2, 3, 4, 4, 5]
print("Sequence 1:", are_all_unique(sequence1)) 
print("Sequence 2:", are_all_unique(sequence2))  

Sequence 1: True
Sequence 2: False


# 7 Create a program to add two integers >0 without using the plus operator.

In [20]:
def add_without_plus(a, b):
    while b != 0:
        # Calculate the carry 
        carry = a & b
        # Sum without considering the carry
        a = a ^ b
        # Shift the carry to the left by 1 bit
        b = carry << 1
    return a

# Example usage:
num1 = 10
num2 = 5
print("Sum:", add_without_plus(num1, num2)) 


Sum: 15


# 8 Create a program to convert dates from yyyy-mm-dd to dd-mm-yyyyy.

In [22]:
def convert_date(date):
    # Split the date string into its components
    parts = date.split('-')
    # Rearrange the components in the desired order
    new_date = parts[2] + '-' + parts[1] + '-' + parts[0]
    return new_date

# Example usage:
date = '2024-06-15'
print("Original date:", date)
print("Converted date:", convert_date(date))  

Original date: 2024-06-15
Converted date: 15-06-2024


# 9 Write a Python program to find yesterday’s, today’s and tomorrow’s date

In [24]:
from datetime import datetime, timedelta

def find_dates():
    # Get today's date
    today = datetime.now().date()
    
    # Calculate yesterday's and tomorrow's date
    yesterday = today - timedelta(days=1)
    tomorrow = today + timedelta(days=1)
    
    return yesterday, today, tomorrow

# Example usage:
yesterday, today, tomorrow = find_dates()
print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)


Yesterday's date: 2024-06-14
Today's date: 2024-06-15
Tomorrow's date: 2024-06-16


# 10 How to create 1D, 2D and 3D arrays?

In [25]:
import numpy as np
# creating the list
list = [100, 200, 300, 400]
# creating 1-d array
n = np.array(list)
print(n)

[100 200 300 400]


In [26]:
# Create a 2-dimensional array with 3 rows and 4 columns
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Print the array
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# Create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
arr = np.array(nested_list)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
